package gradesTracker;

import java.util.HashSet;
import java.util.Set;

/**
 * ComponentesFormacion generated by hbm2java
 */
public class ComponentesFormacion implements java.io.Serializable {

	private char id;
	private String descripcion;
	private Set cursoses = new HashSet(0);

	public ComponentesFormacion() {
	}

	public ComponentesFormacion(char id) {
		this.id = id;
	}

	public ComponentesFormacion(char id, String descripcion, Set cursoses) {
		this.id = id;
		this.descripcion = descripcion;
		this.cursoses = cursoses;
	}

	public char getId() {
		return this.id;
	}

	public void setId(char id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getCursoses() {
		return this.cursoses;
	}

	public void setCursoses(Set cursoses) {
		this.cursoses = cursoses;
	}

}
