// default package
// Generated 10/07/2014 12:37:06 AM by Hibernate Tools 3.4.0.CR1
package gradesTracker;
import java.util.HashSet;
import java.util.Set;

/**
 * Curriculas generated by hbm2java
 */
public class Curriculas implements java.io.Serializable {

	private int id;
	private Integer anhoInicio;
	private Integer anhoFin;
	private String descripcion;
	private String spreadsheetkey;
	private Set cursoses = new HashSet(0);

	public Curriculas() {
	}

	public Curriculas(int id, String spreadsheetkey) {
		this.id = id;
		this.spreadsheetkey = spreadsheetkey;
	}

	public Curriculas(int id, Integer anhoInicio, Integer anhoFin,
			String descripcion, String spreadsheetkey, Set cursoses) {
		this.id = id;
		this.anhoInicio = anhoInicio;
		this.anhoFin = anhoFin;
		this.descripcion = descripcion;
		this.spreadsheetkey = spreadsheetkey;
		this.cursoses = cursoses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getAnhoInicio() {
		return this.anhoInicio;
	}

	public void setAnhoInicio(Integer anhoInicio) {
		this.anhoInicio = anhoInicio;
	}

	public Integer getAnhoFin() {
		return this.anhoFin;
	}

	public void setAnhoFin(Integer anhoFin) {
		this.anhoFin = anhoFin;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getSpreadsheetkey() {
		return this.spreadsheetkey;
	}

	public void setSpreadsheetkey(String spreadsheetkey) {
		this.spreadsheetkey = spreadsheetkey;
	}

	public Set getCursoses() {
		return this.cursoses;
	}

	public void setCursoses(Set cursoses) {
		this.cursoses = cursoses;
	}

}
