// default package
// Generated 10/07/2014 12:37:06 AM by Hibernate Tools 3.4.0.CR1
package gradesTracker;
import java.util.HashSet;
import java.util.Set;

/**
 * CursosProgramados generated by hbm2java
 */
public class CursosProgramados implements java.io.Serializable {

	private CursosProgramadosId id;
	private Cursos cursos;
	private short anhoDictado;
	private Character turno;
	private char cicloDictado;
	private String spreadsheetkey;
	private char tipoCatedra;
	private Set matriculases = new HashSet(0);

	public CursosProgramados() {
	}

	public CursosProgramados(CursosProgramadosId id, Cursos cursos,
			short anhoDictado, char cicloDictado, char tipoCatedra) {
		this.id = id;
		this.cursos = cursos;
		this.anhoDictado = anhoDictado;
		this.cicloDictado = cicloDictado;
		this.tipoCatedra = tipoCatedra;
	}

	public CursosProgramados(CursosProgramadosId id, Cursos cursos,
			short anhoDictado, Character turno, char cicloDictado,
			String spreadsheetkey, char tipoCatedra, Set matriculases) {
		this.id = id;
		this.cursos = cursos;
		this.anhoDictado = anhoDictado;
		this.turno = turno;
		this.cicloDictado = cicloDictado;
		this.spreadsheetkey = spreadsheetkey;
		this.tipoCatedra = tipoCatedra;
		this.matriculases = matriculases;
	}

	public CursosProgramadosId getId() {
		return this.id;
	}

	public void setId(CursosProgramadosId id) {
		this.id = id;
	}

	public Cursos getCursos() {
		return this.cursos;
	}

	public void setCursos(Cursos cursos) {
		this.cursos = cursos;
	}

	public short getAnhoDictado() {
		return this.anhoDictado;
	}

	public void setAnhoDictado(short anhoDictado) {
		this.anhoDictado = anhoDictado;
	}

	public Character getTurno() {
		return this.turno;
	}

	public void setTurno(Character turno) {
		this.turno = turno;
	}

	public char getCicloDictado() {
		return this.cicloDictado;
	}

	public void setCicloDictado(char cicloDictado) {
		this.cicloDictado = cicloDictado;
	}

	public String getSpreadsheetkey() {
		return this.spreadsheetkey;
	}

	public void setSpreadsheetkey(String spreadsheetkey) {
		this.spreadsheetkey = spreadsheetkey;
	}

	public char getTipoCatedra() {
		return this.tipoCatedra;
	}

	public void setTipoCatedra(char tipoCatedra) {
		this.tipoCatedra = tipoCatedra;
	}

	public Set getMatriculases() {
		return this.matriculases;
	}

	public void setMatriculases(Set matriculases) {
		this.matriculases = matriculases;
	}

}
