// default package
// Generated 10/07/2014 12:37:06 AM by Hibernate Tools 3.4.0.CR1
package gradesTracker;
import java.util.HashSet;
import java.util.Set;

/**
 * Cursos generated by hbm2java
 */
public class Cursos implements java.io.Serializable {

	private String id;
	private Curriculas curriculas;
	private ComponentesFormacion componentesFormacion;
	private String nombre;
	private int creditos;
	private Integer prerequisitosCreditos;
	private Byte horasTeoria;
	private Byte horasSemiPresecial;
	private Byte horasTeoricoPractico;
	private Byte horasPractica;
	private byte semestre;
	private String prerequisitos;
	private Set cursosProgramadoses = new HashSet(0);

	public Cursos() {
	}

	public Cursos(String id, Curriculas curriculas,
			ComponentesFormacion componentesFormacion, String nombre,
			int creditos, byte semestre) {
		this.id = id;
		this.curriculas = curriculas;
		this.componentesFormacion = componentesFormacion;
		this.nombre = nombre;
		this.creditos = creditos;
		this.semestre = semestre;
	}

	public Cursos(String id, Curriculas curriculas,
			ComponentesFormacion componentesFormacion, String nombre,
			int creditos, Integer prerequisitosCreditos, Byte horasTeoria,
			Byte horasSemiPresecial, Byte horasTeoricoPractico,
			Byte horasPractica, byte semestre, String prerequisitos,
			Set cursosProgramadoses) {
		this.id = id;
		this.curriculas = curriculas;
		this.componentesFormacion = componentesFormacion;
		this.nombre = nombre;
		this.creditos = creditos;
		this.prerequisitosCreditos = prerequisitosCreditos;
		this.horasTeoria = horasTeoria;
		this.horasSemiPresecial = horasSemiPresecial;
		this.horasTeoricoPractico = horasTeoricoPractico;
		this.horasPractica = horasPractica;
		this.semestre = semestre;
		this.prerequisitos = prerequisitos;
		this.cursosProgramadoses = cursosProgramadoses;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Curriculas getCurriculas() {
		return this.curriculas;
	}

	public void setCurriculas(Curriculas curriculas) {
		this.curriculas = curriculas;
	}

	public ComponentesFormacion getComponentesFormacion() {
		return this.componentesFormacion;
	}

	public void setComponentesFormacion(
			ComponentesFormacion componentesFormacion) {
		this.componentesFormacion = componentesFormacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getCreditos() {
		return this.creditos;
	}

	public void setCreditos(int creditos) {
		this.creditos = creditos;
	}

	public Integer getPrerequisitosCreditos() {
		return this.prerequisitosCreditos;
	}

	public void setPrerequisitosCreditos(Integer prerequisitosCreditos) {
		this.prerequisitosCreditos = prerequisitosCreditos;
	}

	public Byte getHorasTeoria() {
		return this.horasTeoria;
	}

	public void setHorasTeoria(Byte horasTeoria) {
		this.horasTeoria = horasTeoria;
	}

	public Byte getHorasSemiPresecial() {
		return this.horasSemiPresecial;
	}

	public void setHorasSemiPresecial(Byte horasSemiPresecial) {
		this.horasSemiPresecial = horasSemiPresecial;
	}

	public Byte getHorasTeoricoPractico() {
		return this.horasTeoricoPractico;
	}

	public void setHorasTeoricoPractico(Byte horasTeoricoPractico) {
		this.horasTeoricoPractico = horasTeoricoPractico;
	}

	public Byte getHorasPractica() {
		return this.horasPractica;
	}

	public void setHorasPractica(Byte horasPractica) {
		this.horasPractica = horasPractica;
	}

	public byte getSemestre() {
		return this.semestre;
	}

	public void setSemestre(byte semestre) {
		this.semestre = semestre;
	}

	public String getPrerequisitos() {
		return this.prerequisitos;
	}

	public void setPrerequisitos(String prerequisitos) {
		this.prerequisitos = prerequisitos;
	}

	public Set getCursosProgramadoses() {
		return this.cursosProgramadoses;
	}

	public void setCursosProgramadoses(Set cursosProgramadoses) {
		this.cursosProgramadoses = cursosProgramadoses;
	}

}
