// default package
// Generated 10/07/2014 12:37:06 AM by Hibernate Tools 3.4.0.CR1
package gradesTracker;
/**
 * CursosProgramadosId generated by hbm2java
 */
public class CursosProgramadosId implements java.io.Serializable {

	private String id;
	private String cursoId;

	public CursosProgramadosId() {
	}

	public CursosProgramadosId(String id, String cursoId) {
		this.id = id;
		this.cursoId = cursoId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCursoId() {
		return this.cursoId;
	}

	public void setCursoId(String cursoId) {
		this.cursoId = cursoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CursosProgramadosId))
			return false;
		CursosProgramadosId castOther = (CursosProgramadosId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getCursoId() == castOther.getCursoId()) || (this
						.getCursoId() != null && castOther.getCursoId() != null && this
						.getCursoId().equals(castOther.getCursoId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getCursoId() == null ? 0 : this.getCursoId().hashCode());
		return result;
	}

}
