// default package
// Generated 10/07/2014 12:37:06 AM by Hibernate Tools 3.4.0.CR1
package gradesTracker;
/**
 * MatriculasId generated by hbm2java
 */
public class MatriculasId implements java.io.Serializable {

	private int id;
	private String cursosId;
	private String cursosProgramadosId;

	public MatriculasId() {
	}

	public MatriculasId(int id, String cursosId, String cursosProgramadosId) {
		this.id = id;
		this.cursosId = cursosId;
		this.cursosProgramadosId = cursosProgramadosId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCursosId() {
		return this.cursosId;
	}

	public void setCursosId(String cursosId) {
		this.cursosId = cursosId;
	}

	public String getCursosProgramadosId() {
		return this.cursosProgramadosId;
	}

	public void setCursosProgramadosId(String cursosProgramadosId) {
		this.cursosProgramadosId = cursosProgramadosId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MatriculasId))
			return false;
		MatriculasId castOther = (MatriculasId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getCursosId() == castOther.getCursosId()) || (this
						.getCursosId() != null
						&& castOther.getCursosId() != null && this
						.getCursosId().equals(castOther.getCursosId())))
				&& ((this.getCursosProgramadosId() == castOther
						.getCursosProgramadosId()) || (this
						.getCursosProgramadosId() != null
						&& castOther.getCursosProgramadosId() != null && this
						.getCursosProgramadosId().equals(
								castOther.getCursosProgramadosId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getCursosId() == null ? 0 : this.getCursosId().hashCode());
		result = 37
				* result
				+ (getCursosProgramadosId() == null ? 0 : this
						.getCursosProgramadosId().hashCode());
		return result;
	}

}
