// default package
// Generated 10/07/2014 12:37:06 AM by Hibernate Tools 3.4.0.CR1
package gradesTracker;
/**
 * Matriculas generated by hbm2java
 */
public class Matriculas implements java.io.Serializable {

	private MatriculasId id;
	private Usuarios usuarios;
	private CursosProgramados cursosProgramados;
	private Byte notaFinal;
	private String observacion;
	private String letras;
	private String matriculasCursosId;

	public Matriculas() {
	}

	public Matriculas(MatriculasId id, Usuarios usuarios,
			CursosProgramados cursosProgramados, String matriculasCursosId) {
		this.id = id;
		this.usuarios = usuarios;
		this.cursosProgramados = cursosProgramados;
		this.matriculasCursosId = matriculasCursosId;
	}

	public Matriculas(MatriculasId id, Usuarios usuarios,
			CursosProgramados cursosProgramados, Byte notaFinal,
			String observacion, String letras, String matriculasCursosId) {
		this.id = id;
		this.usuarios = usuarios;
		this.cursosProgramados = cursosProgramados;
		this.notaFinal = notaFinal;
		this.observacion = observacion;
		this.letras = letras;
		this.matriculasCursosId = matriculasCursosId;
	}

	public MatriculasId getId() {
		return this.id;
	}

	public void setId(MatriculasId id) {
		this.id = id;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public CursosProgramados getCursosProgramados() {
		return this.cursosProgramados;
	}

	public void setCursosProgramados(CursosProgramados cursosProgramados) {
		this.cursosProgramados = cursosProgramados;
	}

	public Byte getNotaFinal() {
		return this.notaFinal;
	}

	public void setNotaFinal(Byte notaFinal) {
		this.notaFinal = notaFinal;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public String getLetras() {
		return this.letras;
	}

	public void setLetras(String letras) {
		this.letras = letras;
	}

	public String getMatriculasCursosId() {
		return this.matriculasCursosId;
	}

	public void setMatriculasCursosId(String matriculasCursosId) {
		this.matriculasCursosId = matriculasCursosId;
	}

}
