// default package
// Generated 10/07/2014 12:37:06 AM by Hibernate Tools 3.4.0.CR1
package gradesTracker;
import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	private Integer id;
	private String nombreRol;
	private String descripcion;
	private Set rolesUsuarioses = new HashSet(0);

	public Roles() {
	}

	public Roles(String nombreRol, String descripcion, Set rolesUsuarioses) {
		this.nombreRol = nombreRol;
		this.descripcion = descripcion;
		this.rolesUsuarioses = rolesUsuarioses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombreRol() {
		return this.nombreRol;
	}

	public void setNombreRol(String nombreRol) {
		this.nombreRol = nombreRol;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getRolesUsuarioses() {
		return this.rolesUsuarioses;
	}

	public void setRolesUsuarioses(Set rolesUsuarioses) {
		this.rolesUsuarioses = rolesUsuarioses;
	}

}
