// default package
// Generated 10/07/2014 12:37:06 AM by Hibernate Tools 3.4.0.CR1
package gradesTracker;
/**
 * RolesUsuariosId generated by hbm2java
 */
public class RolesUsuariosId implements java.io.Serializable {

	private int id;
	private int usuarioId;
	private int rolId;

	public RolesUsuariosId() {
	}

	public RolesUsuariosId(int id, int usuarioId, int rolId) {
		this.id = id;
		this.usuarioId = usuarioId;
		this.rolId = rolId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	public int getRolId() {
		return this.rolId;
	}

	public void setRolId(int rolId) {
		this.rolId = rolId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolesUsuariosId))
			return false;
		RolesUsuariosId castOther = (RolesUsuariosId) other;

		return (this.getId() == castOther.getId())
				&& (this.getUsuarioId() == castOther.getUsuarioId())
				&& (this.getRolId() == castOther.getRolId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getUsuarioId();
		result = 37 * result + this.getRolId();
		return result;
	}

}
