// default package
// Generated 10/07/2014 12:37:06 AM by Hibernate Tools 3.4.0.CR1
package gradesTracker;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String nombres;
	private String apellidos;
	private String correo;
	private Byte bloqueado;
	private Date ultimoIngreso;
	private Date fechaRegistro;
	private Date fechaNacimiento;
	private Byte comprobado;
	private Set rolesUsuarioses = new HashSet(0);
	private Set matriculases = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String username, String password, String nombres,
			String apellidos) {
		this.username = username;
		this.password = password;
		this.nombres = nombres;
		this.apellidos = apellidos;
	}

	public Usuarios(String username, String password, String nombres,
			String apellidos, String correo, Byte bloqueado,
			Date ultimoIngreso, Date fechaRegistro, Date fechaNacimiento,
			Byte comprobado, Set rolesUsuarioses, Set matriculases) {
		this.username = username;
		this.password = password;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.correo = correo;
		this.bloqueado = bloqueado;
		this.ultimoIngreso = ultimoIngreso;
		this.fechaRegistro = fechaRegistro;
		this.fechaNacimiento = fechaNacimiento;
		this.comprobado = comprobado;
		this.rolesUsuarioses = rolesUsuarioses;
		this.matriculases = matriculases;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Byte getBloqueado() {
		return this.bloqueado;
	}

	public void setBloqueado(Byte bloqueado) {
		this.bloqueado = bloqueado;
	}

	public Date getUltimoIngreso() {
		return this.ultimoIngreso;
	}

	public void setUltimoIngreso(Date ultimoIngreso) {
		this.ultimoIngreso = ultimoIngreso;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public Byte getComprobado() {
		return this.comprobado;
	}

	public void setComprobado(Byte comprobado) {
		this.comprobado = comprobado;
	}

	public Set getRolesUsuarioses() {
		return this.rolesUsuarioses;
	}

	public void setRolesUsuarioses(Set rolesUsuarioses) {
		this.rolesUsuarioses = rolesUsuarioses;
	}

	public Set getMatriculases() {
		return this.matriculases;
	}

	public void setMatriculases(Set matriculases) {
		this.matriculases = matriculases;
	}

}
